const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const source=name=>fs.readFileSync(path.join(__dirname,'..',name),'utf8');
function analytics(hostname='globeeuk.github.io',seed={}){
 const requests=[],store=new Map(Object.entries(seed)),toggle={textContent:'',attrs:{},addEventListener(k,fn){this[k]=fn;},setAttribute(k,v){this.attrs[k]=v;}},status={textContent:''};
 const document={title:'Globee',cookie:'_ga=old; _ga_YRRY654LS1=old',referrer:'https://example.org/?private=yes',head:{appendChild:s=>requests.push(s)},createElement:()=>({}),querySelectorAll:s=>s==='[data-analytics-toggle]'?[toggle]:s==='[data-analytics-status]'?[status]:[],addEventListener(){}};
 const ctx={document,location:{hostname,origin:'https://'+hostname,pathname:'/plans.html',search:'?q=private-name&age=3-5'},URL,Date,localStorage:{getItem:k=>store.get(k),setItem:(k,v)=>store.set(k,v),removeItem:k=>store.delete(k)}};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(source('analytics.js'),ctx);return {ctx,toggle,status,requests,store};
}
test('Cookieless analytics starts by default, strips sensitive filters and supports immediate opt-out',()=>{const a=analytics();assert.equal(a.requests.length,1);assert(a.requests[0].src.endsWith('G-YRRY654LS1'));const events=a.ctx.dataLayer.map(x=>Array.from(x));assert(events.some(x=>x[0]==='consent'&&x[1]==='default'&&x[2].analytics_storage==='denied'));assert(!events.some(x=>JSON.stringify(x).includes('granted')));assert.equal(events.filter(x=>x[0]==='event'&&x[1]==='page_view').length,1);assert(!JSON.stringify(events).includes('private-name'));assert(!JSON.stringify(events).includes('3-5'));a.ctx.globeeTrack('switch_view',{view:'map',query:'private'});assert(!JSON.stringify(a.ctx.dataLayer).includes('private'));a.toggle.click();const count=a.ctx.dataLayer.length;a.ctx.globeeTrack('switch_view',{view:'list'});assert.equal(a.ctx.dataLayer.length,count);assert(a.ctx['ga-disable-G-YRRY654LS1']);assert.equal(a.store.get('globee-analytics-opt-out'),'true');assert.equal(a.toggle.textContent,'Resume site analytics');});
test('A previous refusal remains opted out and can be reversed without a second tag load',()=>{const a=analytics('globeeuk.github.io',{'globee-analytics-choice':'denied'});assert.equal(a.requests.length,0);assert.equal(a.toggle.textContent,'Resume site analytics');a.toggle.click();assert.equal(a.requests.length,1);assert.equal(a.store.has('globee-analytics-choice'),false);assert.equal(a.store.has('globee-analytics-opt-out'),false);});
test('Local QA never contacts Google Analytics',()=>{const a=analytics('127.0.0.1');assert.equal(a.requests.length,0);assert.equal(a.ctx.dataLayer,undefined);});
test('Every public page removes the consent popup and offers a direct analytics opt-out',()=>{for(const name of ['index.html','plans.html','halloween.html','privacy.html','exeter/index.html','exeter/this-weekend/index.html','exeter/free-things-to-do/index.html','exeter/rainy-day/index.html']){const html=source(name);assert(!html.includes('id="analytics-choice"'),name);assert(!html.includes('data-cookie-settings'),name);assert(html.includes('data-analytics-toggle'),name);assert(html.includes('analytics.js?v=stats1'),name);}});
function loader(fetch){const updates=[],status={innerHTML:'',parts:[],append(n){this.parts.push(n);}},snap={schema:1,fetchedAt:'2026-09-01T10:00:00Z',master:[{name:'saved'}],events:[{name:'saved'}]};const ctx={console,Date,JSON,Promise,AbortController,setTimeout,clearTimeout,fetch,localStorage:{getItem(){return null;},setItem(){}},document:{getElementById:()=>status,createTextNode:t=>t,createElement:()=>({addEventListener(){}})},CustomEvent:class{constructor(name,arg){this.detail=arg.detail;}},GLOBEE_SNAPSHOT:snap,GLOBEE_EDITORIAL:{},GlobeeDB:{validate(m,e){if(!m.length||!e.length)throw Error('empty');},parseCSV(s){if(s==='bad')throw Error('bad');return [{name:s}];},normalise:(m,e)=>m},dispatchEvent:e=>updates.push(e.detail)};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(source('db-loader.js'),ctx);return {updates,status};}
test('Loss of connection retains saved results and offers retry',async()=>{const a=loader(()=>Promise.reject(Error('offline')));await new Promise(setImmediate);assert.equal(a.updates.length,0);assert(a.status.parts.some(p=>typeof p==='string'&&p.includes('saved directory')));assert(a.status.parts.some(p=>p.textContent==='Refresh'));});
test('Live refresh replaces data only after both sheets succeed',async()=>{const a=loader(async url=>({ok:true,text:async()=>url.includes('gid=0&')?'new master':'new events'}));await new Promise(setImmediate);assert.equal(a.updates.length,1);assert.equal(a.updates[0].places[0].name,'new master');const bad=loader(async url=>({ok:true,text:async()=>url.includes('gid=0&')?'new master':'bad'}));await new Promise(setImmediate);assert.equal(bad.updates.length,0);});
